---
- name: Deploy Nginx instance {{ instance_index }}
  debug:
    msg: "Deploying Nginx instance number {{ instance_index }}"
    
- name: Pull nginx Docker image
  docker_image:
    name: nginx
    source: pull

- name: Copying Index File
  copy:
    src: files/index.html
    dest: /tmp/site-content/

- name: Copying Nginx Configuration
  copy:
    src: files/nginx.conf
    dest: /tmp/site-content/nginx.conf

- name: Run nginx Docker container
  docker_container:
    name: "nginx-{{ instance_index }}"
    image: nginx
    state: started
    ports:
      - "108{{ instance_index }}:1080"
    volumes:
      - "/tmp/site-content/index.html:/usr/share/nginx/html/index.html:ro"
      - "/tmp/site-content/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
