---
- name: Deploy Nginx instance {{ instance_index }}
  debug:
    msg: "Deploying Nginx instance {{ instance_index }}"

- name: Pull nginx Docker image
  docker_image:
    name: nginx:latest
    source: pull

- name: Create directory for site content
  file:
    path: "/tmp/site-content-{{ instance_index }}"
    state: directory

- name: Copying Index File
  copy:
    src: files/index.html
    dest: "/tmp/site-content-{{ instance_index }}/index.html"
    
- name: Copying Nginx Configuration
  copy:
    src: files/nginx.conf
    dest: /tmp/site-content-{{ instance_index }}/nginx.conf
    
- name: Replace server number on index
  replace:
    path: "/tmp/site-content-{{ instance_index }}/index.html"
    regexp: '#server#'
    replace: '{{ instance_index }}'

- name: Replace server number on conf
  replace:
    path: "/tmp/site-content-{{ instance_index }}/nginx.conf"
    regexp: '#server#'
    replace: '{{ instance_index }}'

- name: Run nginx Docker container
  docker_container:
    name: "nginx-{{ instance_index }}"
    image: nginx:latest
    state: started
    ports:
      - "108{{ instance_index }}:1080"
    volumes:
      - "/tmp/site-content-{{ instance_index }}/index.html:/usr/share/nginx/html/index.html:ro"
      - "/tmp/site-content-{{ instance_index }}/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
