---
- name: Modifiying configuration for {{ backend_type }}-{{ item }}
  debug:
    msg: "Modifiying configuration for {{ backend_type }}-{{ item }}"

- name: "Get infos on container {{ backend_type }}-{{ item }}"
  community.docker.docker_container_info:
    name: "{{ backend_type }}-{{ item }}"
  register: container_results

- name: Replace server number on index
  replace:
    path: "/tmp/haproxy/haproxy.cfg"
    regexp: '# {{ backend_type }}-backend'
    replace: 'server {{ backend_type }}-{{ item }} {{ container_results.container.NetworkSettings.IPAddress }}:{{ port_range }}{{ item }} check\n  # {{ backend_type }}-backend'
  when: container_results.exists