---
- name: Deploy HAProxy Server
  debug:
    msg: "Deploying HAProxy Server"

- name: Pull haproxy Docker image
  docker_image:
    name: haproxy:3.0.3
    source: pull

- name: Copying haproxy Configuration
  copy:
    src: files/haproxy.cfg
    dest: /tmp/haproxy/

- name: Add nginx servers to haproxy.cfg
  include_tasks: nginx_config.yml
  loop: "{{ range(nginx_number) | list }}"
  when: nginx_number is defined

- name: Run haproxy Docker container
  docker_container:
    name: haproxy
    image: haproxy:3.0.3
    state: started
    ports:
      - "80:80"
      - "8404:8404"
    volumes:
      - "/tmp/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
