- name: Pull haproxy Docker image
  docker_image:
    name: haproxy:3.0.3
    source: pull

- name: Copying haproxy Configuration
  copy:
    src: files/haproxy.cfg
    dest: /tmp/haproxy/

- name: Run haproxy Docker container
  docker_container:
    name: haproxy
    image: haproxy:3.0.3
    state: started
    ports:
      - "80:80"
      - "8404:8404"
    volumes:
      - "/tmp/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
