---
- name: Print iteration number
  debug:
    msg: "Modifiying configuration for nginx-{{ item }}"

- name: Run docker inspect command
  shell: "docker inspect -f '{{ '{{' }} range .NetworkSettings.Networks }}{{ .IPAddress }}{{ '{{' }} end }}' nginx-{{ item }}"
  register: container_ip

- name: Replace server number on index
  replace:
    path: "/tmp/haproxy/haproxy.cfg"
    regexp: '# nginx-backend'
    replace: 'server nginx-{{ item }} {{ container_ip }}:108{{ item }} check\n  # nginx-backend'