- hosts: cluster
  become: yes

  vars:
    echoserver: 2
    nginx: 2

  tasks:

    - name: Install docker and dependecies
      include_role:
        name: docker

    - name: Deploy Nginx instances
      include_role:
        name: nginx
      vars:
        instance_index: "{{ item }}"
      loop: "{{ range(nginx) | list }}"

    - name: Deploy echoserver instances
      include_role:
        name: echoserver
      vars:
        instance_index: "{{ item }}"
      loop: "{{ range(echoserver) | list }}"

    - name: Deploy haproxy instances
      include_role:
        name: haproxy
      vars:
        echoserver_number: "{{ echoserver }}"
        nginx_number: "{{ nginx }}"
