- name: Run nginx container
  hosts: cluster
  become: True
  tasks:
    - name: Pull nginx Docker image
      docker_image:
        name: nginx
        source: pull

    - name: Copying Index File
      copy: 
        src: files/index.html 
        dest: /tmp/site-content/

    - name: Copying Nginx Configuration
      copy:
        src: files/nginx.conf
        dest: /tmp/site-content/nginx.conf

    - name: Run nginx Docker container
      docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "1080:1080"
        volumes:
          - "/tmp/site-content:/usr/share/nginx/html:ro"
          - "/tmp/site-content/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
