---
- name: Deploy Echoserver instance {{ instance_index }}
  debug:
    msg: "Deploying Echoserver instance {{ instance_index }}"

- name: Pull echoserver image
  docker_image:
    name: gcr.io/google_containers/echoserver:1.8
    source: pull

- name: Run echoserver container
  docker_container:
    name: "echoserver-{{ instance_index }}"
    image: gcr.io/google_containers/echoserver:1.8
    state: started
    ports:
      - "808{{ instance_index }}:808{{ instance_index }}"
